x-defaults: &defaults
  restart: unless-stopped
  logging:
    driver: none
  networks:
    - traefik-proxy

services:
  klipper:
    <<: *defaults
    container_name: klipper
    devices:
      - /dev/tty3dPrinter:/dev/ttyUSB0
    group_add:
      - 995
    image: mkuf/klipper:latest
    command: >
      -I /opt/printer_data/run/klipper.tty
      -a /opt/printer_data/run/klipper.sock
      -l /opt/printer_data/logs/klippy.log
      /opt/printer_data/config/printer.cfg
    volumes:
      - .:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs

  moonraker:
    <<: *defaults
    container_name: moonraker
    image: mkuf/moonraker:latest
    depends_on:
      klipper:
        condition: service_started
    labels:
      traefik.enable: true
      traefik.http.services.moonraker.loadbalancer.server.port: 7125
      traefik.http.routers.moonraker.entrypoints: "websecure"
      traefik.http.routers.moonraker.rule: Host(`3d.x000.dev`) && PathRegexp(`^/(websocket|printer|api|access|machine|server)`)
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - .:/opt/printer_data/config
      - ./moonraker.secrets:/opt/printer_data/moonraker.secrets

  fluidd:
    <<: *defaults
    container_name: fluidd
    image: ghcr.io/fluidd-core/fluidd:latest
    labels:
      traefik.enable: true
      traefik.http.services.fluidd.loadbalancer.server.port: 80
      traefik.http.routers.fluidd.rule: Host(`3d.x000.dev`)
      traefik.http.routers.fluidd.entrypoints: "websecure"

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true

volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  moonraker-db:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
